version: "3.6"

services:
    db:
        image: mariadb:10.3.6
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
           - ${PWD}/volume/mysql:/var/lib/mysql
           - ${PWD}/volume/mysql_conf:/etc/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - "8000:80"
        environment:
            PMA_HOST: db