version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:3.7.10-management-alpine"
    restart: always
    networks:
      - rabbitmq-network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COKIE=my_secret_rabbitmq_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  rabbitmq-network:
    driver: bridge