version: "3.6"

services:
   mssql:
     image: microsoft/mssql-server-linux:2017-latest
     ports:
       - "1433:1433"
     volumes:
       - ${PWD}/volumes/mssql_data:/var/opt/mssql/data
       - ${PWD}/volumes/mssql_log:/var/opt/mssql/log
       - ${PWD}/volumes/mssql_backup:/var/opt/mssql/backup
     environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Alterplanning-2018"